### ISSUE TITLE
msmtpd oblivious to incoming connections in a container

### ISSUE THREAD

**Issue by schongallam** [marlam/msmtp#157]
I'm having a strange socket issue, and not sure where else to turn.  I'm building the `master` branch from source in a container (called "msmtp"), and configuring msmtpd to relay everything to an SMTP server in another container, with networking orchestrated by docker compose.  I have encountered the following behavior:
- If I exec into the container, and run, for instance, `nc localhost 25`, msmtpd responds as expected and happily transmits my message to the next host, aka "otherserver".
- If I exec into another container on the same docker network, and run `nc msmtp 25`, it yields `Connection refused.` (Yet, the connection is accepted if I make a different program listen on port 25 within the msmtp container)
- If I try to connect to msmtpd from the docker host machine, using the assigned port mapping (i.e. `nc localhost 2508`, see config below for context), msmtpd is oblivious to the incoming connection (unlike anything else I set to listen on that port).  nc will try to send the first chunk of data for me but as soon as I enter a newline, the connection closes without any feedback (and msmtpd logs nothing).
  - Debugging in this scenario, In msmtpd.c, main(): listen() returns fine (line 846 in the github version) but accept() (line 872) never detects the connection. msmtpd doesn't log anything, because it doesn't detect anything to log. Even while msmtpd is ignoring an outside connection, accept() can still respond to (and properly log) incoming connections from within the container and it returns a valid file descriptor.

I don't think its a docker issue, a firewall issue or a routing issue, because other programs can listen on port 25 without problem.

Any ideas why msmtpd alone can't seem to listen to connections coming in from outside the container?  I've configured a dozen other SMTP servers as basic relays like this, and this behavior is unique to msmtp so far.

Thank you in advance for any thoughts you can share.

My msmtprc file:
```
account default
host otherserver
```

My docker-compose.yml:
```
services:
  ...
  otherserver:
    build:
      context: "./images/otherserver"
    image: otherserver-image:latest
    ports:
      - 127.0.0.1:25:25
  msmtp:
    build:
      context: "./images/msmtp"
      args:
        APP_VERSION: "master"
        RELAYHOST: "otherserver"
    image: my-msmtp-image:latest
    ports:
      - 127.0.0.1:2508:25
```

My Dockerfile:
```
FROM my-debian-trixie-image:latest
ARG APP_VERSION=master
ARG RELAYHOST=otherserver
RUN apt -y update && apt -y upgrade \
  && apt -y install automake libtool gettext texinfo pkg-config libgnutls28-dev \
  && git clone https://git.marlam.de/git/msmtp.git \
  && cd msmtp \
  && git checkout $APP_VERSION \
  && autoreconf -i \
  && ./configure \
  && make \
  && make install \
  && printf "account default\nhost ${RELAYHOST}\n" > /usr/local/etc/msmtprc
CMD ["msmtpd"]

# Workaround for msmtpd not aware of incoming network connections:
#CMD nc -lk -p 25 -c 'msmtpd --inetd'
```

(using ncat as nc for the -c feature)
